name: Build and Deploy Vite/Vue App

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'Deployment Environment'
        required: false
        default: 'production'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Use your project's Node version

      - name: Install dependencies
        run: npm install
        working-directory: ./flowchat

      - name: Build
        run: npm run build
        working-directory: ./flowchat

      # Example: Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./flowchat
